-- Run once through `uv run python manage.py init-db` or Supabase SQL Editor.
-- Idempotent: existing notes are retained.
CREATE TABLE IF NOT EXISTS public.note (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Only the server's Postgres connection accesses notes; no direct Data API access.
ALTER TABLE public.note ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.note FROM anon, authenticated;
